stages:
- stage: Build
  jobs:
  - template: build.yml
    parameters:
      jobName: Build_dev
      vmImage: $(vmImage)
      environment: dev
      azureSubscription: 'azureRm'
      namespace: $(namespace)
      aksCommonName: $(aksCommonName)
      locationShort: $(locationShort)

  - template: build.yml
    parameters:
      jobName: Build_qa
      vmImage: $(vmImage)
      environment: qa
      azureSubscription: 'azureRm'
      namespace: $(namespace)
      aksCommonName: $(aksCommonName)
      locationShort: $(locationShort)
      
  - template: build.yml
    parameters:
      jobName: Build_prod
      vmImage: $(vmImage)
      environment: prod
      azureSubscription: 'azureRm'
      namespace: $(namespace)
      aksCommonName: $(aksCommonName)
      locationShort: $(locationShort)
      
- stage: Deploy_dev
  dependsOn: [Build]
  jobs:
  - template: deploy.yml
    parameters:
      deployment: Deploy_dev
      vmImage: $(vmImage)
      environment: dev
      azureSubscription: 'azureRm'
      namespace: $(namespace)
      aksCommonName: $(aksCommonName)
      locationShort: $(locationShort)

- stage: Deploy_qa
  dependsOn: [Build, Deploy_dev]
  jobs:
  - template: deploy.yml
    parameters:
      deployment: Deploy_qa
      vmImage: $(vmImage)
      environment: qa
      azureSubscription: 'azureRm'
      namespace: $(namespace)
      aksCommonName: $(aksCommonName)
      locationShort: $(locationShort)

- stage: Deploy_prod
  dependsOn: [Build, Deploy_qa]
  jobs:
  - template: deploy.yml
    parameters:
      deployment: Deploy_prod
      vmImage: $(vmImage)
      environment: prod
      azureSubscription: 'azureRm'
      namespace: $(namespace)
      aksCommonName: $(aksCommonName)
      locationShort: $(locationShort)
