stages:
- stage: Build
  jobs:
  - template: build.yml
    parameters:
      jobName: Build_dev
      vmImage: $(vmImage)
      environment: dev
      azureSubscription: 'azure-team1-dev-contributor'
      namespace: $(namespace)

  - template: build.yml
    parameters:
      jobName: Build_qa
      vmImage: $(vmImage)
      environment: qa
      azureSubscription: 'azure-team1-qa-contributor'
      namespace: $(namespace)
      
  - template: build.yml
    parameters:
      jobName: Build_prod
      vmImage: $(vmImage)
      environment: prod
      azureSubscription: 'azure-team1-prod-contributor'
      namespace: $(namespace)
      
- stage: Deploy_dev
  dependsOn: [Build]
  jobs:
  - template: deploy.yml
    parameters:
      deployment: Deploy_dev
      vmImage: $(vmImage)
      environment: dev
      azureSubscription: 'azure-team1-dev-contributor'
      namespace: $(namespace)

- stage: Deploy_qa
  dependsOn: [Build, Deploy_dev]
  jobs:
  - template: deploy.yml
    parameters:
      deployment: Deploy_qa
      vmImage: $(vmImage)
      environment: qa
      azureSubscription: 'azure-team1-qa-contributor'
      namespace: $(namespace)

- stage: Deploy_prod
  dependsOn: [Build, Deploy_qa]
  jobs:
  - template: deploy.yml
    parameters:
      deployment: Deploy_prod
      vmImage: $(vmImage)
      environment: prod
      azureSubscription: 'azure-team1-prod-contributor'
      namespace: $(namespace)
